# Generated by Django 5.1.4 on 2025-03-22 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_subscription_tariff_duration'),
        ('profiles', '0003_alter_profile_tg_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='created_at',
        ),
        migrations.AddField(
            model_name='subscription',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_subscription', to='profiles.profile', verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('expired_at', models.DateTimeField(verbose_name='Дата истечения')),
                ('is_actual', models.BooleanField(default=False, verbose_name='Актуально?')),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_payments', to='payments.subscription', verbose_name='Связь с подпиской')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.tariff', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
