# Generated by Django 5.1.4 on 2025-03-22 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payments_expired_at'),
        ('profiles', '0003_alter_profile_tg_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivatedTrialPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='Профиль')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.tariff', verbose_name='Тарифф')),
            ],
            options={
                'verbose_name': 'Пробный период',
                'verbose_name_plural': 'Пробные периоды',
            },
        ),
    ]
