# Generated by Django 5.1.4 on 2025-03-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_activatedtrialperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='status',
            field=models.CharField(choices=[('WR', 'В работе'), ('AC', 'Принято')], default='WR', verbose_name='Статус'),
        ),
    ]
