# Generated by Django 5.1.4 on 2025-04-03 15:30

import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_payments_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='photo',
            field=models.ImageField(null=True, upload_to=payments.models.upload_to_tariff_photo, verbose_name='Превью тарифа'),
        ),
    ]
