# Generated by Django 5.1.4 on 2025-04-03 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_tariff_photo'),
        ('profiles', '0003_alter_profile_tg_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo', models.CharField(max_length=10, verbose_name='Промокод')),
                ('remained', models.IntegerField(verbose_name='Осталось использований')),
                ('discount', models.IntegerField(help_text='руб.', verbose_name='Скидка')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активно?')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_promocodes', to='payments.tariff', verbose_name='Тарифф')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
        migrations.CreateModel(
            name='ActivatedPromocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('promocode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.promocode')),
            ],
        ),
    ]
