# Generated by Django 5.1.4 on 2025-04-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_promocode_activatedpromocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='activatedpromocode',
            name='buyed',
            field=models.BooleanField(default=False, verbose_name='Купили?'),
        ),
    ]
