# Generated by Django 5.1.4 on 2025-04-04 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_activatedpromocode_buyed'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='promocode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_promocode', to='payments.promocode'),
        ),
    ]
