# Generated by Django 5.1.4 on 2025-04-05 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_payments_promocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_promocode', to='payments.promocode'),
        ),
    ]
