# Generated by Django 5.1.4 on 2025-07-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_alter_payments_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='trial',
            field=models.BooleanField(default=False, verbose_name='Пробная?'),
        ),
    ]
