# Generated by Django 5.1.4 on 2025-11-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_payments_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Приватка?'),
        ),
    ]
