# Generated by Django 5.1.4 on 2025-11-17 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_tariff_is_private'),
        ('profiles', '0009_remove_freebetfilter_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservedTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название топика')),
                ('thread_id', models.BigIntegerField(verbose_name='Id топика')),
            ],
            options={
                'verbose_name': 'Топик приватки',
                'verbose_name_plural': 'Топики для приватки',
            },
        ),
        migrations.CreateModel(
            name='ObservedTopicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_profit', models.FloatField(verbose_name='Макмимальный % дохода')),
                ('min_profit', models.FloatField(verbose_name='Минимальный % дохода')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.observedtopic', verbose_name='Топик')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateObservingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активно?')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('topic', models.ManyToManyField(to='payments.observedtopicsettings')),
            ],
        ),
    ]
