# Generated by Django 5.1.4 on 2025-11-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_observedtopic_observedtopicsettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observedtopic',
            name='slug',
            field=models.CharField(default='', verbose_name='Кеш ключ'),
        ),
    ]
