# Generated by Django 5.1.4 on 2025-11-17 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_observedtopic_slug'),
        ('profiles', '0009_remove_freebetfilter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='observedtopicsettings',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='observedtopicsettings',
            name='max_profit',
            field=models.FloatField(null=True, verbose_name='Макмимальный % дохода'),
        ),
        migrations.AlterField(
            model_name='observedtopicsettings',
            name='min_profit',
            field=models.FloatField(null=True, verbose_name='Минимальный % дохода'),
        ),
        migrations.DeleteModel(
            name='PrivateObservingSettings',
        ),
    ]
