# Generated by Django 5.1.4 on 2025-11-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_observedtopicsettings_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observedtopicsettings',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активен?'),
        ),
    ]
