# Generated by Django 5.1.4 on 2025-03-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('tg_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Телеграм айди')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
