# Generated by Django 5.1.4 on 2025-04-11 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_tg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='referrer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_referrer', to='profiles.profile', verbose_name='Реферрер'),
        ),
        migrations.CreateModel(
            name='ReferalProgramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.BigIntegerField(verbose_name='Баланс партнерской программы')),
                ('referal_count', models.BigIntegerField(verbose_name='Количество рефераллов')),
                ('total_earnings', models.BigIntegerField(verbose_name='Всего заработано')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='Реферрер')),
            ],
            options={
                'verbose_name': 'Аккаунт реферальной программы',
                'verbose_name_plural': 'Аккаунты реферальной программы',
            },
        ),
    ]
