# Generated by Django 5.1.4 on 2025-07-29 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_referalprogramaccount_referal_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmakerFilterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(verbose_name='Букмекеры')),
                ('max_coef_first_book', models.FloatField(null=True, verbose_name='Максималньый коэффициент первая бк')),
                ('min_coef_first_book', models.FloatField(null=True, verbose_name='Минимальный коэффициент первая бк')),
                ('max_coef_second_book', models.FloatField(null=True, verbose_name='Максималньый коэффициент вторая бк')),
                ('min_coef_second_book', models.FloatField(null=True, verbose_name='Минимальный коэффициент вторая бк')),
                ('name', models.CharField(verbose_name='Название')),
                ('surebet_url', models.TextField(null=True, verbose_name='Ссылка на surebet')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='Создатель фильтра')),
            ],
            options={
                'verbose_name': 'Фильтр',
                'verbose_name_plural': 'Фильтр',
            },
        ),
    ]
