# Generated by Django 5.1.4 on 2025-08-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_bookmakerfiltermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmakerfiltermodel',
            name='excluded_bookers',
            field=models.JSONField(default=dict, null=True, verbose_name='Исключенные конторы'),
        ),
    ]
