# Generated by Django 5.1.4 on 2025-11-04 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_bookmakerfiltermodel_excluded_bookers'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreebetFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(verbose_name='Букмекеры')),
                ('name', models.CharField(verbose_name='Название')),
                ('surebet_url', models.TextField(null=True, verbose_name='Ссылка на surebet')),
                ('excluded_bookers', models.JSONField(default=dict, null=True, verbose_name='Исключенные конторы')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='Создатель фильтра')),
            ],
            options={
                'verbose_name': 'Фильтр для фрибетов',
                'verbose_name_plural': 'Фильтры для фрибетов',
            },
        ),
    ]
