# Generated by Django 5.1.4 on 2025-11-04 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_freebetfilter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freebetfilter',
            name='name',
        ),
    ]
