# Generated by Django 5.1.4 on 2025-03-15 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_alter_profile_tg_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechSupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Тело тикета')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Тикет тех.поддержки',
                'verbose_name_plural': 'Тикеты технической поддержки',
            },
        ),
        migrations.CreateModel(
            name='UpdateTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Тело тикета')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Тикет на обновление',
                'verbose_name_plural': 'Тикеты на обновления',
            },
        ),
    ]
