# Generated by Django 5.1.4 on 2025-03-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='techsupportticket',
            name='status',
            field=models.CharField(choices=[('NW', 'Новое'), ('WR', 'В работе'), ('CL', 'Закрыт')], default='NW', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='updateticket',
            name='status',
            field=models.CharField(choices=[('NW', 'Новое'), ('AC', 'Принято')], default='NW', verbose_name='Статус'),
        ),
    ]
